include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**
    - test/**/*.mocks.dart
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false